apiVersion: v1
kind: Pod
metadata:
  name: rook-tools
  namespace: rook
spec:
  containers:
  - name: rook-tools
    image: inspireso/rook-toolbox:latest
    imagePullPolicy: Always
    args: ["sleep", "36500d"]
    env:
    - name: ROOKD_ADMIN_SECRET
      valueFrom:
        secretKeyRef:
          name: mon
          key: admin-secret
    securityContext:
      privileged: true
    volumeMounts:
    - mountPath: /dev
      name: dev
    - mountPath: /sys/bus
      name: sysbus
    - mountPath: /lib/modules
      name: libmodules
  volumes:
  - name: dev
    hostPath:
      path: /dev
  - name: sysbus
    hostPath:
      path: /sys/bus
  - name: libmodules
    hostPath:
      path: /lib/modules