FROM alpine:latest

MAINTAINER lan.xinen <lan.xinen@inspireso.cn>

RUN apk add --no-cache --virtual .build-deps \
    gcc \
    libc-dev \
    make \
    openssl-dev \
    pcre-dev \
    zlib-dev \
    linux-headers \
    curl \
    jemalloc-dev