name: Docker

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  push:
    branches: 
      - master
      - BASEIMAGE
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}


jobs:
  java:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3


      # Workaround: https://github.com/docker/build-push-action/issues/461

      # https://github.com/docker/setup-buildx-action
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2

      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Login to registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Extract metadata (tags, labels) for Docker
      # https://github.com/docker/metadata-action
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository }}

      - name: copy rootfs
        run: |
          cd java
          cp -rf ./rootfs ./8/jdk/alpine/
          cp -rf ./rootfs ./8/jdk/onbuild/
          cp -rf ./rootfs ./8/jre/alpine/
          cp -rf ./rootfs ./11/jdk/onbuild/
          cp -rf ./rootfs ./17/jdk/onbuild/

      # Build and push Docker image with Buildx (don't push on PR)
      # https://github.com/docker/build-push-action
      - name: 8-jdk-onbuild
        uses: docker/build-push-action@v4
        with:
          context: ./java/8-jdk-onbuild/
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/java:8-jdk-onbuild
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: 8-jdk-alpine
        uses: docker/build-push-action@v4
        with:
          context: ./java/8-jdk-alpine/
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/java:8-jdk-alpine
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: 8-jre-alpine
        uses: docker/build-push-action@v4
        with:
          context: ./java/8-jre-alpine/
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/java:8-jre-alpine
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: 11-jdk-onbuild
        uses: docker/build-push-action@v4
        with:
          context: ./java/11-jdk-onbuild/
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/java:11-jdk-onbuild
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: 17-jdk-onbuild
        uses: docker/build-push-action@v4
        with:
          context: ./java/17-jdk-onbuild/
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/java:17-jdk-onbuild
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max          
          